kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: workdir
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi # make this bigger in production
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ipfs-cluster
  labels:
    name: ipfs-cluster
spec:
  replicas: 3
  selector:
    matchLabels: 
      app: ipfs-cluster
  template:
    metadata:
      labels:
        app: ipfs-cluster
        role: peer
    spec:

      volumes:
      - name: workdir
        persistentVolumeClaim:
          claimName: workdir

      containers:
      - name: ipfs-cluster
        image: "docker.io/ipfs/ipfs-cluster:latest"
        envFrom: 
          - configMapRef:
              name: ipfs-cluster-config
        ports:
        - containerPort: 4001
          name: "swarm"
          protocol: "TCP"
        - containerPort: 5001
          name: "api"
          protocol: "TCP"
        - containerPort: 9094
          name: "clusterapi"
          protocol: "TCP"
        - containerPort: 9095
          name: "clusterproxy"
          protocol: "TCP"
        - containerPort: 9096
          name: "cluster"
          protocol: "TCP"
      - name: go-ipfs
        image: "ipfs/go-ipfs"
        envFrom: 
          - configMapRef:
              name: ipfs-cluster-config
        ports:
            - name: swarm
              protocol: TCP
              containerPort: 4001
            - name: swarm-udp
              protocol: UDP
              containerPort: 4002
            - name: ipfs-daemon-api
              protocol: TCP
              containerPort: 5001
            - name: ws
              protocol: TCP
              containerPort: 8081
            - name: http
              protocol: TCP
              containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: ipfs-service
  labels:
    app: ipfs-cluster
spec:
  ports:
  - port: 8080
    name: api
  selector:
    app: ipfs-cluster

---
apiVersion: networking.k8s.io/v1beta1 # for versions before 1.14 use extensions/v1beta1
kind: Ingress
metadata:
  name: example-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
  - host: hello-world.info
    http:
      paths:
      - path: /
        backend:
          serviceName: ipfs-service
          servicePort: 8080